Repository var-co-jp/hackathon-begginers-sample, pull requests merged in 2022-09, with the labels that each got.

#8 [fix] htmlの中身をJinja2記述に変更
  app.py
  static/css/main.css
  static/css/mobile-header.css
  static/css/modal.css
  static/js/addThreadModal.js
  static/js/modal.js
  static/js/pagenation.js
  templates/base.html
  templates/detail.html
  templates/index.html
  templates/mobile-header.html
  templates/modal/add-channel.html
  templates/modal/delete-confirmation.html
  templates/registration/base.html
  templates/registration/login.html
  templates/registration/registration-base.html
  templates/registration/signup.html
  templates/sidebar.html
Labels: Frontend

#14 チャンネルのデータをJSに渡してindexページに表示
  app.py
  models.py
  static/css/base.css
  static/css/registration.css
  static/js/pagenation.js
  templates/base.html
  templates/index.html
  templates/registration/login.html
  templates/registration/signup.html
Labels: Frontend

#16 詳細ページにチャンネルの説明を追加（UI）
  static/css/base.css
  static/css/detail.css
  templates/detail.html
Labels: Frontend

#19 チャンネル登録時機能
  app.py
  models.py
  static/css/mobile-header.css
  static/css/modal.css
  templates/modal/add-channel.html
Labels: Frontend, Backend

#26 エラー画面
  app.py
  static/css/base.css
  static/css/color.css
  static/css/error.css
  static/js/error.js
  templates/error/404.html
  templates/error/500.html
  templates/error/base.html
  templates/error/error.html
Labels: Frontend, Backend

#27 チャンネル詳細ページ
  app.py
  models.py
  static/css/detail.css
  static/css/main.css
  static/css/mobile-header.css
  static/js/pagenation.js
  static/js/scroll-message.js
  templates/base.html
  templates/detail.html
  templates/index.html
  templates/mobile-header.html
  templates/sidebar.html
Labels: Frontend, Backend

#28 Features/#7
  app.py
  models.py
  requirements.txt
  templates/hello.html
  user.py
Labels: Backend

#30 サインアップ のフロントとバック繋ぎ込み
  app.py
  static/css/detail.css
  static/css/registration.css
  templates/detail.html
  templates/registration/login.html
  templates/registration/signup.html
Labels: Frontend

#34 フロントとバックのログインのつなぎ
  static/css/registration.css
  templates/registration/login.html
Labels: Frontend

#35 チャンネル削除機能
  app.py
  static/css/base.css
  static/css/main.css
  static/js/modal.js
  static/js/pagenation.js
  templates/index.html
  templates/modal/delete-confirmation.html
Labels: Frontend, Backend

#36 [add]session[uid]のロジック作成
  app.py
  templates/hello.html
Labels: Backend

#41 メッセージが空の場合そのままリターン
  app.py
Labels: Backend

#42 [fix] メッセージの横幅を狭くする
  static/css/detail.css
  static/css/sidebar.css
  templates/detail.html
  templates/sidebar.html
Labels: Frontend

#50 チャンネルのアップデート
  app.py
  models.py
  static/css/base.css
  static/css/detail.css
  static/css/main.css
  static/js/modal.js
  static/js/pagenation.js
  static/js/update-channel.js
  templates/base.html
  templates/detail.html
  templates/index.html
  templates/modal/update-channel.html
  templates/registration/login.html
  templates/registration/signup.html
Labels: Frontend

#51 チャンネル作成者のみチャンネル削除できるように変更
  static/js/pagenation.js
  templates/index.html
Labels: Frontend

#56 チャンネルアップデートロジック
  app.py
  models.py
  templates/modal/update-channel.html
Labels: Backend

#59 余分な関数の削除
  app.py
  models.py
  requirements.txt
  templates/hello.html
  views.py
Labels: Backend

#64 メッセージにユーザーネームを表示（フロント）
  static/css/detail.css
  templates/detail.html
Labels: Frontend

#65 不要なコード削除
  static/css/color.css
  static/css/mobile-header.css
  static/css/modal.css
  static/css/registration.css
  static/css/sidebar.css
  templates/sidebar.html
Labels: Frontend

#68 余分な関数の削除
  app.py
  models.py
Labels: Backend
